### PR TITLE
 Enhance DLA Catalogs realism with NHI errors, SNR cuts and reduced completeness

### PR DESCRIPTION
**Pull request by HiramHerrera**
## Pull Request:  Enhance DLA Catalogs realism with NHI errors, SNR cuts and reduced completeness

This Pull Request implements changes to create more realistic DLA catalogs.

### Changes Included

1. **New Script:** `lyatools/scripts/make_snr_cat.py`
   - Originally Allyson Brodzeller's [`snr_mocks.py` script](https://github.com/cosmodesi/desi-lya-bao/blob/dlatools/dla_scripts/snr_mocks.py).
   - **Note:** This script requires the `desispec` package.

2. **Modifications to `lyatools/scripts/make_dla_cat.py`:**
   - The output file containing all the HCDs added to mocks (including those with NHI < 20.30) will now be called `hcd_truth_catalog.fits` for clarity. This also avoids having to delete previous realization catalogs to re-run `lyatools`.
   - Merges the SNR catalog generated by Allyson's script into the HCD catalog.
   - Introduces random errors in the NHI measurement based on a specified sigma value.
   - Applies a mask cut based on SNR, in addition to the previous behavior of cutting based on NHI values.
   - Implements a flat random cut for completeness. A placeholder is available for future enhancement to support completeness as a function of NHI and SNR.

### Workflow Considerations

This PR does not yet integrate `make_snr_cat.py` into the `lyatools` workflow output scripts. The required workflow order is as follows:

1. `lyatools/scripts/make_z_cat.py`
2. `lyatools/scripts/make_bal_cat.py`
3. `lyatools/scripts/make_snr_cat.py` (requires the previous two catalogs)
4. `lyatools/scripts/make_dla_cat.py` (requires the SNR catalog)

### CODE REVIEW

**Comment by andreufont** [comment]
@HiramHerrera - what will be the name of the new, trimmed file? It would be good to give it a new name as well, to avoid confusion with previous runs

**Comment by HiramHerrera** [comment]
> @HiramHerrera - what will be the name of the new, trimmed file? It would be good to give it a new name as well, to avoid confusion with previous runs

@andreufont. The new trimmed catalog, with NHI errors added will be called: `dla_cat_nhi_{mask_nhi_cut}_snr_{mask_snr_cut}_completeness_{completeness}.fits`

For the baseline we are proposing this would be: `dla_cat_nhi_20.30_snr_2.0_completeness_0.75.fits`

Quite a long name but very informative. Do you have other recommendation?

I would also like to confirm if we are going to add NHI errors to these catalogs.

**Comment by andreufont** [comment]
A long, informative sounds good. Thanks!

I would not add NHI errors for now, let's keep things simple.

**Comment by andreicuceu** [comment]
The two scripts are now integrated in lyatools, and I tested/debugged everything. We are good to go.

**Pull request merged**
